### PR TITLE
Integration of the english OGL content for The Rad Hack

### PR DESCRIPTION
**Pull request by brunobord**
I cannot thank enough @fermcg for his fantastic help by providing the content I would've been sad to extract by hand myself.

### CODE REVIEW

**Comment by brunobord** [comment]
will close #1

**Comment by brunobord** [comment]
to @fermcg if you notice any mistake or typo in my text, please add a comment here ; we've got some time, let's try to make it pixel-perfect :-)

**Comment by fermcg** [comment]
Great news Bruno! I'll review it when I get home. Tomorrow it's a holiday in Brazil. I hope I can get the translation done. I'll also try to identify which blocks of text match or are similar to TBH's to help other translators who already had TBH translated.

**Comment by brunobord** [comment]
thank you @fermcg for all your remarks. I've finally found enough time to check your checks and fix what was needed.

**Pull request merged**
